CREATE TABLE tb_manutencoes
(
    manutencao_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    maquina_id    BIGINT                                  NOT NULL,
    user_id       UUID                                    NOT NULL,
    data_criacao  TIMESTAMP WITHOUT TIME ZONE,
    data_limite   TIMESTAMP WITHOUT TIME ZONE,
    ativo         BOOLEAN,
    descricao     VARCHAR(255),
    prioridade    VARCHAR(8),
    tipo          VARCHAR(10),
    conclusao     VARCHAR(10),
    data_conclusao   TIMESTAMP WITHOUT TIME ZONE,
    relatorio     VARCHAR(255),
    CONSTRAINT pk_tb_manutencoes PRIMARY KEY (manutencao_id)
);

ALTER TABLE tb_manutencoes
    ADD CONSTRAINT FK_TB_MANUTENCOES_ON_MAQUINA FOREIGN KEY (maquina_id) REFERENCES tb_maquinas (maquina_id);

ALTER TABLE tb_manutencoes
    ADD CONSTRAINT FK_TB_MANUTENCOES_ON_USER FOREIGN KEY (user_id) REFERENCES tb_users (user_id);

CREATE TABLE tb_registros
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_registro                   TIMESTAMP WITHOUT TIME ZONE,
    quantidade_maquinas             BIGINT,
    quantidade_pessoas              BIGINT,
    quantidade_manutencoes_abertas  BIGINT,
    quantidade_manutencoes_fechadas BIGINT,
    quantidade_sucesso              BIGINT,
    quantidade_falha                BIGINT,
    quantidade_adiamento            BIGINT,
    CONSTRAINT pk_tb_registros PRIMARY KEY (id)
);